In [28]:
import pandas as pd
import numpy as np

In [4]:
#Current working directory
import os 
print(os.getcwd())

c:\Users\Lenovo\Desktop\AI_ML_Journey\ML_maths_journey\pandas_tutorial\data

In [5]:
#Reading all file formats

df_csv=pd.read_csv("results.csv")
df_parquet=pd.read_parquet("results.parquet")
df_feather=pd.read_feather("results.feather")
df_olympics=pd.read_excel("olympics-data.xlsx")

print(df_csv.head(5))
print(df_parquet.head(5))
print(df_feather.head(5))
print(df_olympics.head(5))

     year    type discipline                     event                     as  \
0  1912.0  Summer     Tennis    Singles, Men (Olympic)  Jean-François Blanchy
1  1912.0  Summer     Tennis    Doubles, Men (Olympic)  Jean-François Blanchy
2  1920.0  Summer     Tennis    Singles, Men (Olympic)  Jean-François Blanchy
3  1920.0  Summer     Tennis  Doubles, Mixed (Olympic)  Jean-François Blanchy
4  1920.0  Summer     Tennis    Doubles, Men (Olympic)  Jean-François Blanchy

   athlete_id  noc             team  place   tied medal
0           1  FRA              NaN   17.0   True   NaN
1           1  FRA   Jean Montariol    NaN  False   NaN
2           1  FRA              NaN   32.0   True   NaN
3           1  FRA  Jeanne Vaussard    8.0   True   NaN
4           1  FRA  Jacques Brugnon    4.0  False   NaN
     year    type discipline                     event                     as  \
0  1912.0  Summer     Tennis    Singles, Men (Olympic)  Jean-François Blanchy
1  1912.0  Summer     Tennis    Doubles, Men (Olympic)  Jean-François Blanchy
2  1920.0  Summer     Tennis    Singles, Men (Olympic)  Jean-François Blanchy
3  1920.0  Summer     Tennis  Doubles, Mixed (Olympic)  Jean-François Blanchy
4  1920.0  Summer     Tennis    Doubles, Men (Olympic)  Jean-François Blanchy

   athlete_id  noc             team  place   tied medal
0           1  FRA             None   17.0   True  None
1           1  FRA   Jean Montariol    NaN  False  None
2           1  FRA             None   32.0   True  None
3           1  FRA  Jeanne Vaussard    8.0   True  None
4           1  FRA  Jacques Brugnon    4.0  False  None
     year    type discipline                     event                     as  \
0  1912.0  Summer     Tennis    Singles, Men (Olympic)  Jean-François Blanchy
1  1912.0  Summer     Tennis    Doubles, Men (Olympic)  Jean-François Blanchy
2  1920.0  Summer     Tennis    Singles, Men (Olympic)  Jean-François Blanchy
3  1920.0  Summer     Tennis  Doubles, Mixed (Olympic)  Jean-François Blanchy
4  1920.0  Summer     Tennis    Doubles, Men (Olympic)  Jean-François Blanchy

   athlete_id  noc             team  place   tied medal
0           1  FRA             None   17.0   True  None
1           1  FRA   Jean Montariol    NaN  False  None
2           1  FRA             None   32.0   True  None
3           1  FRA  Jeanne Vaussard    8.0   True  None
4           1  FRA  Jacques Brugnon    4.0  False  None
   athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux
1           2         Arnaud Boetsch  1969-04-01       Meulan
2           3           Jean Borotra  1898-08-13     Biarritz
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe
4           5           Albert Canet  1878-04-17   Wandsworth

            born_region born_country     NOC  height_cm  weight_kg   died_date
0               Gironde          FRA  France        NaN        NaN  1960-10-02
1              Yvelines          FRA  France      183.0       76.0         NaN
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17
3                 Paris          FRA  France      168.0       64.0  1978-03-20
4               England          GBR  France        NaN        NaN  1930-07-25

In [6]:
#Random samples
df_csv.sample(10)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
249726,2008.0,Summer,Diving (Aquatics),"Platform, Men (Olympic)",Riley McCormick,116091,CAN,NaN,16.0,False,NaN
102034,1976.0,Summer,Swimming (Aquatics),"400 metres Freestyle, Women (Olympic)",Susan Barnard,46971,GBR,NaN,19.0,False,NaN
37384,1964.0,Summer,Fencing,"Foil, Team, Women (Olympic)",Tatyana Samusenko,20969,URS,Soviet Union,2.0,False,Silver
149348,1924.0,Summer,Athletics,"Long Jump, Men (Olympic)",Cheruvari Lakshmanan,71393,IND,NaN,NaN,False,NaN
113761,1964.0,Summer,Swimming (Aquatics),"100 metres Freestyle, Women (Olympic)",Jeanne Hallock,51044,USA,NaN,9.0,True,NaN
9447,1952.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",László Bánhegyi,5673,HUN,Hungary,13.0,True,NaN
185069,1956.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Men (Olympic)",Ernst Hinterseer,86655,AUT,NaN,6.0,False,NaN
53690,1952.0,Summer,Artistic Gymnastics (Gymnastics),"Team All-Around, Women (Olympic)",Irma Walther,28577,GER,Unified Team of Germany,5.0,False,NaN
103199,1932.0,Summer,Swimming (Aquatics),"400 metres Freestyle, Men (Olympic)",Norman Wainwright,47428,GBR,NaN,3.0,False,NaN
139143,1988.0,Summer,Athletics,"800 metres, Men (Olympic)",William Taramai,66632,COK,NaN,8.0,False,NaN

Accessing records

In [7]:
#loc and iloc

#loc->use integer and labels
first_three_rows=df_csv.loc[0:3,["year","type","discipline","event"]]
first_athlethes=df_csv.loc[:10,["as","athlete_id"]]

#iloc->only integers
fancy_records=df_csv.iloc[[0,55,92],[2,5,8]]

#updating values
first_three_rows.loc[0,"type"]="BuffaloSauce"

print(first_three_rows)
print(first_athlethes)
print(fancy_records)

     year          type discipline                     event
0  1912.0  BuffaloSauce     Tennis    Singles, Men (Olympic)
1  1912.0        Summer     Tennis    Doubles, Men (Olympic)
2  1920.0        Summer     Tennis    Singles, Men (Olympic)
3  1920.0        Summer     Tennis  Doubles, Mixed (Olympic)
                       as  athlete_id
0   Jean-François Blanchy           1
1   Jean-François Blanchy           1
2   Jean-François Blanchy           1
3   Jean-François Blanchy           1
4   Jean-François Blanchy           1
5          Arnaud Boetsch           2
6          Arnaud Boetsch           2
7            Jean Borotra           3
8            Jean Borotra           3
9            Jean Borotra           3
10        Jacques Brugnon           4
   discipline  athlete_id  place
0      Tennis           1   17.0
55     Tennis          14    3.0
92     Tennis          23    9.0

Accessing Data with Pandas

In [8]:
df_feather.at[1,"type"]
df_feather.iat[1,3]

'Doubles, Men (Olympic)'

Sorting

In [9]:
sorted_values=df_csv.sort_values(["type","as","athlete_id"],ascending=[1,0,1]).iloc[0:10,0:5]
print(sorted_values)

          year    type               discipline  \
74588   1936.0  Summer                 Handball
227618  2004.0  Summer  Canoe Sprint (Canoeing)
227619  2004.0  Summer  Canoe Sprint (Canoeing)
227620  2012.0  Summer  Canoe Sprint (Canoeing)
228424  2004.0  Summer                Athletics
304717  2020.0  Summer      Football (Football)
84895   1968.0  Summer                   Rowing
84896   1972.0  Summer                   Rowing
84897   1976.0  Summer                   Rowing
122756  1980.0  Summer            Weightlifting

                                           event                as
74588                    Handball, Men (Olympic)     Ștefan Zoller
227618  Kayak Doubles, 500 metres, Men (Olympic)     Ștefan Vasile
227619  Kayak Fours, 1,000 metres, Men (Olympic)     Ștefan Vasile
227620  Kayak Fours, 1,000 metres, Men (Olympic)     Ștefan Vasile
228424                  High Jump, Men (Olympic)  Ștefan Vasilache
304717                   Football, Men (Olympic)  Ștefan Târnovanu
84895                 Coxed Fours, Men (Olympic)      Ștefan Tudor
84896                 Coxed Pairs, Men (Olympic)      Ștefan Tudor
84897               Coxless Fours, Men (Olympic)      Ștefan Tudor
122756             Heavyweight II, Men (Olympic)    Ștefan Tașnadi

Querying values

In [15]:
indians=df_csv[df_csv["noc"]=='IND'].sort_values("year",ascending=True).iloc[:3,:7]

recent_indians=df_csv[(df_csv["noc"]=='IND') & (df_csv['year']>2000.0)].sort_values("as").iloc[:20,:5]

last_atheletes=df_csv.query('noc=="IND" & year==2020')

#print(indians)
#print(recent_indians)
print(last_atheletes)

          year    type    discipline                          event  \
222843  2020.0  Summer       Archery      Individual, Men (Olympic)
222844  2020.0  Summer       Archery            Team, Men (Olympic)
227076  2020.0  Summer     Athletics  Discus Throw, Women (Olympic)
232711  2020.0  Summer  Table Tennis         Singles, Men (Olympic)
232712  2020.0  Summer  Table Tennis       Doubles, Mixed (Olympic)
...        ...     ...           ...                            ...
306296  2020.0  Summer        Tennis         Singles, Men (Olympic)
306370  2020.0  Summer        Hockey        Hockey, Women (Olympic)
306403  2020.0  Summer        Hockey          Hockey, Men (Olympic)
306404  2020.0  Summer        Hockey          Hockey, Men (Olympic)
306420  2020.0  Summer          Golf    Individual, Women (Olympic)

                           as  athlete_id  noc          team  place   tied  \
222843          Tarundeep Rai      102875  IND           NaN   17.0   True
222844          Tarundeep Rai      102875  IND         India    8.0  False
227076            Seema Punia      104937  IND           NaN   16.0  False
232711  Sharath Kamal Achanta      107497  IND           NaN   17.0   True
232712  Sharath Kamal Achanta      107497  IND  Manika Batra    9.0   True
...                       ...         ...  ...           ...    ...    ...
306296            Sumit Nagal      147660  IND           NaN   17.0   True
306370          Reena Khokhar      147731  IND         India    NaN  False
306403       Simranjeet Singh      147765  IND         India    3.0  False
306404            Varun Kumar      147766  IND         India    3.0  False
306420           Diksha Dagar      147784  IND           NaN   50.0   True

         medal
222843     NaN
222844     NaN
227076     NaN
232711     NaN
232712     NaN
...        ...
306296     NaN
306370     NaN
306403  Bronze
306404  Bronze
306420     NaN

[135 rows x 11 columns]

Looping through rows

In [11]:
for index,row in indians.iterrows():
    print(row)

year                                     1900.0
type                                     Summer
discipline                            Athletics
event         110 metres Hurdles, Men (Olympic)
as                             Norman Pritchard
Name: 149376, dtype: object
year                                     1900.0
type                                     Summer
discipline                            Athletics
event         200 metres Hurdles, Men (Olympic)
as                             Norman Pritchard
Name: 149377, dtype: object
year                                     1900.0
type                                     Summer
discipline                            Athletics
event         400 metres Hurdles, Men (Olympic)
as                             Norman Pritchard
Name: 149378, dtype: object

In [16]:
df_csv["First_Name"]=df_csv["as"].str.split(' ').str[0]
df_csv["Last_Name"]=df_csv["as"].str.split(' ').str[1]

indians=df_csv.query('noc=="IND"')

print(indians["First_Name"].value_counts().nlargest(5))
print(indians["Last_Name"].value_counts().nlargest(5))

First_Name
Anant      16
Gagan      13
Bandu      12
Leander    11
Sandeep    11
Name: count, dtype: int64
Last_Name
Singh    343
Kumar     77
Ram       34
Lal       21
Chand     20
Name: count, dtype: int64

In [12]:
df_csv.head(5)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [18]:
print("Total events:",len(indians["event"]))
print("Total number of medals won by Indians")
print(indians["medal"].value_counts().nlargest(3))

Total events: 1651
Total number of medals won by Indians
medal
Gold      132
Bronze     61
Silver     22
Name: count, dtype: int64

In [19]:
indians.to_csv("indian_olympics.csv",index=False)

Merging DataFrames

In [20]:
bios=pd.read_csv("bios.csv")
noc_regions=pd.read_csv("noc_regions.csv")
print(bios.columns)
print(noc_regions.columns)

Index(['athlete_id', 'name', 'born_date', 'born_city', 'born_region',
       'born_country', 'NOC', 'height_cm', 'weight_kg', 'died_date'],
      dtype='object')
Index(['NOC', 'region', 'notes'], dtype='object')

In [34]:
filtered_results=df_csv.loc[:,["year","type","discipline","event","athlete_id","medal","team","place","tied"]]
merged_df=pd.merge(filtered_results,bios,left_on='athlete_id',right_on='athlete_id',how='inner')
merged_df=merged_df[merged_df["medal"].notna()].sample(10)
merged_df

,year,type,discipline,event,athlete_id,medal,team,place,tied,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
280916,2020.0,Summer,Tennis,"Doubles, Mixed (Olympic)",131618,Gold,Andrey Rublyov,1.0,False,Anastasiya Pavlyuchenkova,1991-07-03,Samara,Samara,RUS,ROC Russian Federation,177.0,72.0,NaN
114267,1956.0,Summer,Swimming (Aquatics),"400 metres Freestyle, Men (Olympic)",51274,Bronze,NaN,3.0,False,George Breen,1935-07-19,Buffalo,New York,USA,United States,183.0,83.0,2019-11-09
47987,2004.0,Summer,Football (Football),"Football, Women (Olympic)",25379,Bronze,Germany,3.0,False,Pia Wunderlich,1975-01-26,Bad Berleburg,Nordrhein-Westfalen,GER,Germany,173.0,66.0,NaN
156448,1992.0,Summer,Athletics,"High Jump, Men (Olympic)",74812,Bronze,NaN,3.0,True,Artur Partyka,1969-07-25,Stalowa Wola,Podkarpackie,POL,Poland,193.0,71.0,NaN
235006,2012.0,Summer,Hockey,"Hockey, Men (Olympic)",108956,Bronze,Australia,3.0,False,Mark Knowles,1984-03-10,Rockhampton,Queensland,AUS,Australia,183.0,74.0,NaN
118494,1900.0,Summer,Swimming (Aquatics),"Water Polo, Men (Olympic)",53828,Bronze,Libellule de Paris,3.0,True,Jules Clévenot,1875-06-07,Schirmeck,Bas-Rhin,FRA,France,NaN,NaN,1933-09-11
262755,2016.0,Summer,Water Polo (Aquatics),"Water Polo, Men (Olympic)",122199,Gold,Serbia,1.0,False,Dušan Mandić,1994-06-16,Kotor,Kotor,MNE,Serbia,202.0,105.0,NaN
292548,2022.0,Winter,Ski Jumping (Skiing),"Normal Hill, Team, Mixed (Olympic)",138006,Gold,Slovenia,1.0,False,Timi Zajc,2000-04-26,Ljubno,Ljubno,SLO,Slovenia,170.0,60.0,NaN
42760,1952.0,Summer,Fencing,"Sabre, Team, Men (Olympic)",22700,Silver,Italy,2.0,False,Renzo Nostini,1914-05-27,Roma,Roma,ITA,Italy,NaN,NaN,2005-09-30
267311,2016.0,Summer,Sailing,"One Person Dinghy, Women (Olympic)",124893,Gold,NaN,1.0,False,Marit Bouwmeester,1988-06-17,NaN,NaN,NaN,Netherlands,177.0,68.0,NaN

In [38]:
#heights
merged_df["height_class"]=merged_df["height_cm"].apply(lambda x:"Not Available" if pd.isna(x) else "Short" if x<160.0 else "Moderate" if x<185.0 else "Tall")
merged_df[["name","height_cm","height_class"]].sample(5)

                  name  height_cm   height_class
262755    Dušan Mandić      202.0           Tall
114267    George Breen      183.0       Moderate
42760    Renzo Nostini        NaN  Not Available
235006    Mark Knowles      183.0       Moderate
47987   Pia Wunderlich      173.0       Moderate

In [41]:
pivot=pd.pivot_table(merged_df,values="athlete_id",columns="medal",index="event",aggfunc="count",fill_value=0)
print(pivot)

medal                                Bronze  Gold  Silver
event
400 metres Freestyle, Men (Olympic)       1     0       0
Doubles, Mixed (Olympic)                  0     1       0
Football, Women (Olympic)                 1     0       0
High Jump, Men (Olympic)                  1     0       0
Hockey, Men (Olympic)                     1     0       0
Normal Hill, Team, Mixed (Olympic)        0     1       0
One Person Dinghy, Women (Olympic)        0     1       0
Sabre, Team, Men (Olympic)                0     0       1
Water Polo, Men (Olympic)                 1     1       0

In [32]:
merged_df2=pd.merge(bios,noc_regions,left_on='born_region',right_on='region',how='inner')
merged_df.sample(10)

,year,type,discipline,event,athlete_id,medal,team,place,tied,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
246807,2008.0,Summer,Athletics,"400 metres Hurdles, Men (Olympic)",114627,Bronze,NaN,3.0,False,Bershawn Jackson,1983-05-08,Miami,Florida,USA,United States,173.0,69.0,NaN
168408,1960.0,Winter,Cross Country Skiing (Skiing),"10 kilometres, Women (Olympic)",80591,Silver,NaN,2.0,False,Lyubov Kozyreva-Baranova,1929-08-27,Bugry,Leningrad,RUS,Soviet Union,155.0,53.0,2015-06-22
45523,1972.0,Summer,Fencing,"Sabre, Individual, Men (Olympic)",23601,Gold,NaN,1.0,False,Viktor Sidyak,1943-11-24,Anzhero-Sudzhensk,Kemerovo,RUS,Soviet Union,176.0,76.0,NaN
119412,1976.0,Summer,Water Polo (Aquatics),"Water Polo, Men (Olympic)",54302,Silver,Italy,2.0,False,Gianni De Magistris,1950-12-03,Firenze,Firenze,ITA,Italy,185.0,82.0,NaN
205135,1972.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",96029,Silver,United States,2.0,False,Wally Olds,1949-08-17,Warroad,Minnesota,USA,United States,188.0,89.0,2009-01-11
151378,1960.0,Summer,Athletics,"800 metres, Men (Olympic)",72297,Bronze,NaN,3.0,False,George Kerr,1937-10-16,Maryland,Hanover,JAM,Jamaica West Indies Federation,180.0,70.0,2012-06-15
156038,1964.0,Summer,Athletics,"4 × 100 metres Relay, Women (Olympic)",74618,Gold,Poland,1.0,False,Irena Kirszenstein-Szewińska,1946-05-24,NaN,NaN,NaN,Poland,176.0,60.0,2018-06-29
180624,1908.0,Summer,Figure Skating (Skating),"Special Figures, Men (Olympic)",84933,Silver,NaN,2.0,False,Arthur Cumming,1889-05-08,Marylebone,England,GBR,Great Britain,NaN,NaN,1914-05-09
34409,1936.0,Summer,Hockey,"Hockey, Men (Olympic)",19188,Gold,British India,1.0,False,Sayed Muhammad Hussain,1911-10-01,NaN,NaN,NaN,India,NaN,NaN,1977-02-28
40191,1924.0,Summer,Fencing,"Épée, Team, Men (Olympic)",21874,Gold,France,1.0,False,Lucien Gaudin,1886-09-27,Arras,Pas-de-Calais,FRA,France,NaN,NaN,1934-09-23